### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ParadiseFallen** [osm1um/amino.ts#5]
![image](https://user-images.githubusercontent.com/50731756/89673048-5fd78f80-d8ee-11ea-9cd9-2d179d14f346.png)
Error: nodeNC failed:

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:50678
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 50678
}

    at sendMessage (D:\Programs\GitHub\amino.ts\node_modules\sync-rpc\lib\index.js:146:13)
    at D:\Programs\GitHub\amino.ts\node_modules\sync-rpc\lib\index.js:175:25
    at Function.request [as default] (D:\Programs\GitHub\amino.ts\node_modules\sync-request\lib\index.js:28:15)
    at Object.request (D:\Programs\GitHub\amino.ts\build\request.js:10:42)
    at AminoCommunity.set_description (D:\Programs\GitHub\amino.ts\build\components\community\community.js:27:32)
    at Shutdown (D:\Programs\GitHub\amino.ts\build\app.js:19:27)
    at process.<anonymous> (D:\Programs\GitHub\amino.ts\build\app.js:23:28)
    at process.emit (events.js:315:20)
D:\Programs\GitHub\amino.ts\build\request.js:14
        throw new Error(error.body);
        ^

Error
    at Object.request (D:\Programs\GitHub\amino.ts\build\request.js:14:15)
    at AminoCommunity.set_description (D:\Programs\GitHub\amino.ts\build\components\community\community.js:27:32)
    at Shutdown (D:\Programs\GitHub\amino.ts\build\app.js:19:27)
    at process.<anonymous> (D:\Programs\GitHub\amino.ts\build\app.js:23:28)
    at process.emit (events.js:315:20)

**Comment by ParadiseFallen** [comment]
https://github.com/ForbesLindesay/sync-request/issues/127
Not library perfection

**Comment by beryll1um** [comment]
Yes. Will soon have its own implementation.
